name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "pip3 install -r requirements.txt && python3 start.py ICMP 141.24.210.140:80 1000 30 debug=true"
